dist: xenial

language: python

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'

before_script: python -m pip install -r requirements.txt

script: make test

deploy:
  provider: pypi
  user: cmccandless
  password: $PYPI_PASSWORD
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: cmccandless/safepass
    python: '3.6'
